export const SEED = {
  "prayers": [
    {
      "key": "signum_crucis",
      "source": "standard",
      "title_nl": "Kruisteken",
      "title_la": "Signum crucis",
      "text_nl": "In de naam van de Vader en de Zoon en de Heilige Geest.\nAmen.",
      "text_la": "In nómine Patris et Fílii et Spíritus Sancti.\nAmen.",
      "language": "both",
      "category": "standaardgebed",
      "notes": "Klassieke opening",
      "source_url": "https://rkliturgie.nl/links/algemene-of-dagelijkse-gebeden-en-oefeningen"
    },
    {
      "key": "our_father",
      "source": "standard",
      "title_nl": "Onze Vader",
      "title_la": "Pater noster",
      "text_nl": "Onze Vader, die in de hemel zijt,\nuw naam worde geheiligd,\nuw rijk kome,\nuw wil geschiede op aarde zoals in de hemel.\nGeef ons heden ons dagelijks brood\nen vergeef ons onze schulden,\nzoals ook wij vergeven aan onze schuldenaren,\nen breng ons niet in beproeving,\nmaar verlos ons van het kwade.\nAmen.",
      "text_la": "Pater noster, qui es in caelis:\nsanctificétur nomen tuum;\nadvéniat regnum tuum;\nfiat volúntas tua, sicut in caelo, et in terra.\nPanem nostrum quotidiánum da nobis hódie;\net dimítte nobis débita nostra,\nsicut et nos dimíttimus debitóribus nostris;\net ne nos indúcas in tentatiónem;\nsed líbera nos a malo.\nAmen.",
      "language": "both",
      "category": "standaardgebed",
      "notes": "Gebed des Heren.",
      "source_url": "https://rkliturgie.nl/algemene-of-dagelijkse-gebeden-en-oefeningen/onze-vader-gebed-des-heren-pater-noster-oratio-dominica"
    },
    {
      "key": "hail_mary",
      "source": "standard",
      "title_nl": "Wees gegroet",
      "title_la": "Ave Maria",
      "text_nl": "Wees gegroet, Maria, vol van genade,\nde Heer is met u.\nGij zijt de gezegende onder de vrouwen\nen gezegend is Jezus, de vrucht van uw schoot.\nHeilige Maria, Moeder van God,\nbid voor ons, zondaars,\nnu en in het uur van onze dood.\nAmen.",
      "text_la": "Ave María, grátia plena,\nDóminus tecum;\nbenedícta tu in muliéribus,\net benedíctus fructus ventris tui, Iesus.\nSancta María, Mater Dei,\nora pro nobis peccatóribus\nnunc et in hora mortis nostrae.\nAmen.",
      "language": "both",
      "category": "standaardgebed",
      "notes": "Klassiek mariaal gebed.",
      "source_url": "https://rkliturgie.nl/algemene-of-dagelijkse-gebeden-en-oefeningen/wees-gegroet-ave-maria"
    },
    {
      "key": "gloria_patri",
      "source": "standard",
      "title_nl": "Eer aan de Vader",
      "title_la": "Gloria Patri",
      "text_nl": "Eer aan de Vader en de Zoon en de Heilige Geest.\nZoals het was in het begin en nu en altijd\nen in de eeuwen der eeuwen.\nAmen.",
      "text_la": "Glória Patri et Fílio et Spirítui Sancto.\nSicut erat in princípio et nunc et semper\net in saécula saeculórum.\nAmen.",
      "language": "both",
      "category": "standaardgebed",
      "notes": "Korte doxologie.",
      "source_url": "https://rkliturgie.nl/algemene-of-dagelijkse-gebeden-en-oefeningen/eer-aan-de-vader-gloria-patri"
    },
    {
      "key": "salve_regina",
      "source": "standard",
      "title_nl": "Wees gegroet, Koningin",
      "title_la": "Salve Regina",
      "text_nl": "Wees gegroet, Koningin, Moeder van barmhartigheid;\nons leven, onze vreugde en onze hoop, wees gegroet.\nTot u roepen wij, ballingen, kinderen van Eva;\ntot u smeken wij, zuchtend en wenend in dit dal van tranen.\nDaarom dan, onze voorspreekster,\nsla op ons uw barmhartige ogen;\nen toon ons, na deze ballingschap,\nJezus, de gezegende vrucht van uw schoot.\nO goedertieren, o liefdevolle, o zoete Maagd Maria.",
      "text_la": "Salve, Regína, mater misericórdiae;\nvita, dulcédo et spes nostra, salve.\nAd te clamámus, éxsules fílii Evae.\nAd te suspirámus, geméntes et flentes\nin hac lacrimárum valle.\nEia ergo, advocáta nostra,\nillos tuos misericórdes óculos\nad nos convérte.\nEt Iesum, benedíctum fructum ventris tui,\nnobis post hoc exsílium osténde.\nO clemens, o pia, o dulcis Virgo María.",
      "language": "both",
      "category": "maria-antifoon",
      "notes": "Mariale slotantifoon.",
      "source_url": "https://rkliturgie.nl/algemene-of-dagelijkse-gebeden-en-oefeningen/wees-gegroet-koningin-salve-regina"
    },
    {
      "key": "angelus",
      "source": "standard",
      "title_nl": "Engel des Heren",
      "title_la": "Angelus Domini",
      "text_nl": "De Engel des Heren heeft aan Maria geboodschapt,\nEn ze heeft ontvangen van de Heilige Geest.\nWees gegroet...\nZie de dienstmaagd des Heren.\nMij geschiede naar uw woord.\nWees gegroet...\nEn het Woord is vlees geworden.\nEn Het heeft onder ons gewoond.\nWees gegroet...\nBid voor ons, heilige Moeder van God,\nopdat wij de beloften van Christus waardig worden.\n\nLaat ons bidden.\nHeer, wij hebben door de boodschap van de Engel\nde menswording van Christus, uw Zoon, leren kennen,\nwij bidden U:\nstort uw genade in onze harten,\nopdat wij door zijn lijden en kruis gebracht worden\ntot de heerlijkheid van de verrijzenis.\nDoor Christus onze Heer.\nAmen.",
      "text_la": "Ángelus Dómini nuntiávit Maríae\nEt concépit de Spíritu Sancto.\nAve Maria...\nEcce ancílla Dómini.\nFiat mihi secúndum verbum tuum.\nAve Maria...\nEt Verbum caro factum est.\nEt habitávit in nobis.\nAve Maria...\nOra pro nobis, sancta Dei Génitrix,\nut digni efficiámur promissiónibus Christi.\n\nOrémus.\nGrátiam tuam, quaésumus, Dómine,\nméntibus nostris infúnde,\nut qui, Angelo nuntiánte,\nChristi Fílii tui incarnatiónem cognóvimus,\nper passiónem eius et crucem\nad resurrectiónis glóriam perducámur.\nPer Christum Dóminum nostrum.\nAmen.",
      "language": "both",
      "category": "standaardgebed",
      "notes": "Traditioneel middaggebed.",
      "source_url": "https://rkliturgie.nl/algemene-of-dagelijkse-gebeden-en-oefeningen/engel-des-heren-angelus-domini"
    },
    {
      "key": "magnificat",
      "source": "standard",
      "title_nl": "Magnificat",
      "title_la": "Magnificat",
      "text_nl": "Hoog verheft nu mijn ziel de Heer,\nverrukt is mijn geest om God, mijn Verlosser,\nomdat Hij heeft neergezien op zijn geringe dienstmaagd.\nVan heden af prijst elk geslacht mij zalig,\nomdat Hij die machtig is aan mij zijn wonderwerken deed,\nen heilig is zijn Naam.\nBarmhartig is Hij van geslacht tot geslacht\nvoor hen die Hem vrezen.\nHij toont de kracht van zijn arm,\nslaat trotsen van hart uiteen.\nHeersers ontneemt Hij hun troon,\nmaar verheft de geringen.\nDie hongeren overlaadt Hij met gaven,\nen rijken zendt Hij heen met lege handen.\nZijn dienaar Israël heeft Hij zich aangetrokken,\ngedachtig zijn barmhartigheid\nvoor eeuwig jegens Abraham en zijn geslacht,\ngelijk Hij had gezegd tot onze vaderen.",
      "text_la": "Magníficat ánima mea Dóminum,\net exsultávit spíritus meus in Deo salutári meo,\nquia respéxit humilitátem ancíllae suae.\nEcce enim ex hoc beátam me dicent omnes generationes,\nquia fecit mihi magna, qui potens est,\net sanctum nomen eius,\net misericórdia eius a progénie in progénies timéntibus eum.\nFecit poténtiam in bráchio suo,\ndispérsit supérbos mente cordis sui.\nDepósuit poténtes de sede\net exaltávit húmiles.\nEsuriéntes implévit bonis\net dívites dimísit inánes.\nSuscépit Israël púerum suum,\nrecordátus misericórdiae suae,\nsicut locútus est ad patres nostros,\nÁbraham et sémini eius in saécula.",
      "language": "both",
      "category": "evangelielofzang",
      "notes": "Lofzang van Maria.",
      "source_url": "https://rkliturgie.nl/links/algemene-of-dagelijkse-gebeden-en-oefeningen"
    },
    {
      "key": "veni_creator",
      "source": "standard",
      "title_nl": "Kom, Schepper Geest",
      "title_la": "Veni Creator Spiritus",
      "text_nl": "Kom, Schepper Geest, daal tot ons neer,\nhoud Gij bij onze harten inkeer,\nvul met uw hemelse zaligheid\nde ziel, die Gij hebt toebereid.\n\nGij die de Trooster zijt genoemd,\ngeschenk van God, levend en beroemd,\nvuur, liefde en bron, altijd weer,\nzalving van zielen, daal nu neer.",
      "text_la": "Veni, Creátor Spíritus,\nmentes tuórum vísita,\nimple supérna grátia,\nquae tu creásti péctora.\n\nQui díceris Paráclitus,\naltíssimi donum Dei,\nfons vivus, ignis, cáritas,\net spiritális únctio.",
      "language": "both",
      "category": "hymne",
      "notes": "Openingshymne tot de Heilige Geest, verkorte versie voor v1.",
      "source_url": "https://rkliturgie.nl/links/algemene-of-dagelijkse-gebeden-en-oefeningen"
    },
    {
      "key": "anima_christi",
      "source": "standard",
      "title_nl": "Ziel van Christus",
      "title_la": "Anima Christi",
      "text_nl": "Ziel van Christus, heilig mij.\nLichaam van Christus, behoud mij.\nBloed van Christus, bedrink mij.\nWater uit Christus’ zijde, was mij.\nLijden van Christus, sterk mij.\nO goede Jezus, verhoor mij.\nBinnen uw wonden, verberg mij.\nLaat niet toe dat ik van U scheid.\nBescherm mij tegen de boze vijand.\nRoep mij in het uur van mijn dood.\nEn laat mij tot U komen,\nopdat ik U loof met uw heiligen,\nin de eeuwen der eeuwen.\nAmen.",
      "text_la": "Ánima Christi, sanctífica me.\nCorpus Christi, salva me.\nSanguis Christi, inébria me.\nAqua láteris Christi, lava me.\nPássio Christi, confírma me.\nO bone Iesu, exáudi me.\nIntra tua vúlnera abscónde me.\nNe permíttas me separári a te.\nAb hoste malígno defénde me.\nIn hora mortis meae voca me.\nEt iube me veníre ad te,\nut cum Sanctis tuis laudem te,\nin saécula saeculórum.\nAmen.",
      "language": "both",
      "category": "standaardgebed",
      "notes": "Gebed na de communie.",
      "source_url": "https://rkliturgie.nl/links/algemene-of-dagelijkse-gebeden-en-oefeningen"
    },
    {
      "key": "memorare",
      "source": "standard",
      "title_nl": "Gedenk, o allermildste Maagd Maria",
      "title_la": "Memorare",
      "text_nl": "Gedenk, o allermildste Maagd Maria,\ndat het nooit gehoord is,\ndat iemand die tot u zijn toevlucht nam,\nuw hulp inriep en om uw bijstand vroeg,\ndoor u in de steek gelaten werd.\nGesterkt door dit vertrouwen,\nneem ik mijn toevlucht tot u,\no Maagd der maagden, mijn Moeder.\nTot u kom ik, voor u sta ik,\narm en zondig.\nO Moeder van het Woord,\nversmaad mijn woorden niet,\nmaar luister genadig en verhoor mij.\nAmen.",
      "text_la": "Memoráre, o piíssima Virgo María,\nnon esse audítum a sǽculo,\nquemquam ad tua curréntem præsídia,\ntua implorántem auxílio,\ntua peténtem suffrágia,\nesse derelíctum.\nEgo tali animátus confidéntia,\nad te, Virgo Vírginum, Mater, curro;\nad te vénio;\ncoram te gemens peccátor assísto.\nNoli, Mater Verbi,\nverba mea despícere,\nsed audi propítia et exáudi.\nAmen.",
      "language": "both",
      "category": "standaardgebed",
      "notes": "Klassiek mariaal smeekgebed.",
      "source_url": "https://rkliturgie.nl/links/algemene-of-dagelijkse-gebeden-en-oefeningen"
    },
    {
      "key": "regina_caeli",
      "source": "standard",
      "title_nl": "Koningin des hemels",
      "title_la": "Regina caeli",
      "text_nl": "Koningin des hemels, verheug U, alleluia.\nWant Hij die Gij waardig zijt geweest te dragen, alleluia,\nis verrezen zoals Hij gezegd heeft, alleluia.\nBid God voor ons, alleluia.",
      "text_la": "Regína caeli, laetáre, allelúia.\nQuia quem meruísti portáre, allelúia,\nresurréxit, sicut dixit, allelúia.\nOra pro nobis Deum, allelúia.",
      "language": "both",
      "category": "maria-antifoon",
      "notes": "Paastijdse mariale antifoon.",
      "source_url": "https://rkliturgie.nl/links/algemene-of-dagelijkse-gebeden-en-oefeningen"
    },
    {
      "key": "confiteor",
      "source": "standard",
      "title_nl": "Schuldbelijdenis",
      "title_la": "Confiteor",
      "text_nl": "Ik belijd voor de almachtige God,\nvoor de heilige Maria, altijd Maagd,\nvoor de heilige aartsengel Michaël,\nvoor de heilige Johannes de Doper,\nvoor de heilige apostelen Petrus en Paulus,\nvoor alle heiligen\nen voor u, Vader,\ndat ik zeer gezondigd heb,\nin gedachte, woord en daad,\ndoor mijn schuld, door mijn schuld,\ndoor mijn grote schuld.\nDaarom smeek ik de heilige Maria, altijd Maagd,\nde heilige aartsengel Michaël,\nde heilige Johannes de Doper,\nde heilige apostelen Petrus en Paulus,\nalle heiligen,\nen u, Vader,\nvoor mij te bidden tot de Heer, onze God.",
      "text_la": "Confíteor Deo omnipoténti,\nbeátae Maríae semper Vírgini,\nbeáto Michaéli Archángelo,\nbeáto Ioánni Baptístae,\nsanctis Apóstolis Petro et Paulo,\nómnibus Sanctis,\net tibi, Pater,\nquia peccávi nimis\ncogitatióne, verbo et ópere:\nmea culpa, mea culpa,\nmea máxima culpa.\nÍdeo precor beátam Maríam semper Vírginem,\nbeátum Michaélem Archángelum,\nbeátum Ioánnem Baptístam,\nsanctos Apóstolos Petrum et Paulum,\nomnes Sanctos,\net te, Pater,\noráre pro me ad Dóminum Deum nostrum.",
      "language": "both",
      "category": "standaardgebed",
      "notes": "Schuldbelijdenis volgens de buitengewone vorm (Tridentijnse Mis).",
      "source_url": "https://nl.wikipedia.org/wiki/Confiteor"
    },
    {
      "key": "credo",
      "source": "standard",
      "title_nl": "Geloofsbelijdenis",
      "title_la": "Credo",
      "text_nl": "Ik geloof in één God\nde almachtige Vader\nSchepper van hemel en aarde,\nvan al wat zichtbaar en onzichtbaar is.\n\nEn in één Heer, Jezus Christus,\neniggeboren Zoon van God,\nvóór alle tijden geboren uit de Vader.\n\nGod uit God, licht uit licht,\nware God uit de ware God.\nGeboren, niet geschapen,\néén in wezen met de Vader,\nen door Wie alles geschapen is.\n\nHij is voor ons, mensen,\nen omwille van ons heil\nuit de hemel neergedaald.\n\nHij heeft het vlees aangenomen\ndoor de Heilige Geest\nuit de Maagd Maria\nen is mens geworden.\n\nHij werd voor ons gekruisigd,\nHij heeft geleden onder Pontius Pilatus\nen is begraven.\nHij is verrezen op de derde dag,\nvolgens de Schriften.\nHij is opgevaren ten hemel:\nzit aan de rechterhand van de Vader.\n\nHij zal wederkomen in heerlijkheid\nom te oordelen levenden en doden\nen aan Zijn rijk komt geen einde.\n\nIk geloof in de Heilige Geest\nDie Heer is en het leven geeft\nDie voortkomt uit de Vader en de Zoon;\n\nDie met de Vader en de Zoon\ntezamen wordt aanbeden en verheerlijkt;\nDie gesproken heeft door de profeten.\n\nIk geloof in de ene, heilige, katholieke\nen apostolische Kerk.\n\nIk belijd één doopsel\ntot vergeving van de zonden.\n\nIk verwacht de opstanding van de doden\nen het leven van het komend rijk.\n\nAmen.",
      "text_la": "Credo in unum Deum,\nPatrem omnipotentem,\nFactorem coelis et terrae,\nvisibilium omnium et invisibilium.\n\nEt in unum Dominum Iesum Christum,\nFilium Dei unigenitum,\net ex Patre natum ante omnia saecula.\n\nDeum de Deo, Lumen de Lumine,\nDeum verum de Deo vero,\ngenitum non factum,\nconsubstantialem Patri;\nper quem omnia facta sunt.\n\nQui propter nos homines\net propter nostram salutem\ndescendit de caelis.\n\nEt incarnatus est\nde Spiritu Sancto\nex Maria Virgine,\net homo factus est.\n\nCrucifixus etiam pro nobis\nsub Pontio Pilato, passus\net sepultus est.\nEt resurrexit tertia die,\nsecundum Scripturas,\net ascendit in caelum,\nsedet ad dexteram Patris.\n\nEt iterum venturus est cum gloria,\niudicare vivos et mortuos,\ncuius regni non erit finis.\n\nEt in Spiritum Sanctum,\nDominum et vivificantem,\nqui ex Patre Filioque procedit.\n\nQui cum Patre et Filio\nsimul adoratur et conglorificatur:\nqui locutus est per prophetas.\n\nEt unam, sanctam, catholicam\net apostolicam Ecclesiam.\n\nConfiteor unum baptisma\nin remissionem peccatorum.\n\nEt expecto resurrectionem mortuorum,\net vitam venturi saeculi.\n\nAmen.",
      "language": "both",
      "category": "geloofsbelijdenis",
      "notes": "Geloofsbelijdenis van Nicea-Constantinopel, gebeden in de Mis.",
      "source_url": "http://www.katholiek.org/credo.htm"
    },
    {
      "key": "symbolum_apostolorum",
      "source": "standard",
      "title_nl": "Apostolische geloofsbelijdenis",
      "title_la": "Symbolum Apostolicum",
      "text_nl": "Ik geloof in God, de almachtige Vader,\nSchepper van hemel en aarde.\nEn in Jezus Christus, zijn enige Zoon, onze Heer,\ndie ontvangen is van de heilige Geest,\ngeboren uit de Maagd Maria;\ndie geleden heeft onder Pontius Pilatus,\nis gekruisigd, gestorven en begraven;\ndie nedergedaald is ter helle,\nde derde dag verrezen uit de doden;\ndie opgestegen is ten hemel,\nzit aan de rechterhand van God, de almachtige Vader;\nvandaar zal Hij komen oordelen de levenden en de doden.\nIk geloof in de heilige Geest;\nde heilige katholieke kerk,\nde gemeenschap van de heiligen;\nde vergeving van de zonden;\nde verrijzenis van het lichaam;\nen het eeuwig leven.\nAmen.",
      "text_la": "Credo in Deum, Patrem omnipotentem,\ncreatorem caeli et terrae.\nEt in Iesum Christum, Filium eius unicum, Dominum nostrum,\nqui conceptus est de Spiritu Sancto,\nnatus ex Maria Virgine,\npassus sub Pontio Pilato,\ncrucifixus, mortuus et sepultus.\nDescendit ad inferos,\ntertia die resurrexit a mortuis.\nAscendit ad caelos,\nsedet ad dextram Dei Patris omnipotentis.\nInde venturus est iudicare vivos et mortuos.\nCredo in Spiritum Sanctum,\nsanctam Ecclesiam catholicam,\nsanctorum communionem,\nremissionem peccatorum,\ncarnis resurrectionem,\nvitam aeternam.\nAmen.",
      "language": "both",
      "category": "geloofsbelijdenis",
      "notes": "De Twaalf Artikelen van het Geloof; gebeden bij het begin van de rozenkrans.",
      "source_url": "https://www.ewtn.com/catholicism/teachings/prayers-of-the-rosary-in-english-and-latin-164"
    },
    {
      "key": "oratio_fatima",
      "source": "standard",
      "title_nl": "Zuchtgebed van Fatima",
      "title_la": "Oratio Fatima",
      "text_nl": "O mijn Jezus, vergeef ons onze zonden,\nbehoed ons voor het vuur van de hel,\nbreng alle zielen naar de hemel,\nvooral diegenen die Uw barmhartigheid\nhet meeste nodig hebben.",
      "text_la": "Domine Iesu, dimitte nobis debita nostra,\nsalva nos ab igne inferni,\nperduc in caelum omnes animas,\npraesertim eas quae misericordiae tuae maximae indigent.",
      "language": "both",
      "category": "standaardgebed",
      "notes": "Gebeden na elk tientje van de rozenkrans (Fatima, 1917).",
      "source_url": "https://www.ewtn.com/catholicism/teachings/prayers-of-the-rosary-in-english-and-latin-164"
    },
    {
      "key": "alma_redemptoris_mater",
      "source": "standard",
      "title_nl": "Verheven Moeder van de Verlosser",
      "title_la": "Alma Redemptoris Mater",
      "text_nl": "Verheven Moeder van de Verlosser,\ndie altijd zijt de open deur des hemels\nen de ster der zee,\nkom het volk te hulp dat valt en poogt op te staan.\nGij die tot verwondering van de natuur\nuw heilige Schepper hebt gebaard\nen maagd zijt gebleven;\ngij die door Gabriël zijt begroet,\nontferm u over ons, zondaars.",
      "text_la": "Alma Redemptóris Mater,\nquae pérvia caeli porta manes,\net stella maris, succúrre cadénti,\nsúrgere qui curat, pópulo;\ntu quae genuísti, natúra miránte,\ntuum sanctum Genitórem,\nVirgo prius ac postérius,\nGabriélis ab ore sumens illud Ave,\npeccatórum miserére.",
      "language": "both",
      "category": "maria-antifoon",
      "notes": "Maria-antifoon voor de Advent en Kersttijd (eerste zondag van de Advent tot Maria Lichtmis, 2 februari).",
      "source_url": "https://rkliturgie.nl/algemene-of-dagelijkse-gebeden-en-oefeningen/verheven-moeder-van-de-verlosser-alma-redemptoris-mater"
    },
    {
      "key": "ave_regina_caelorum",
      "source": "standard",
      "title_nl": "Gegroet gij, hemelkoningin",
      "title_la": "Ave Regina caelorum",
      "text_nl": "Gegroet gij, hemelkoningin;\ngegroet gij, engelenvorstin;\ngij wortel die het leven draagt;\ngij poort waaruit het licht ons daagt.\nVerheug u, wonderschone Maagd.\nVaarwel en bied uw hulpbetoon,\nwees onze voorspraak bij uw Zoon.",
      "text_la": "Ave, Regína caelórum,\nave, Dómina angelórum,\nsalve, radix, salve, porta,\nex qua mundo lux est orta.\nGaude, Virgo gloriósa,\nsuper omnes speciósa;\nvale, o valde decóra,\net pro nobis Christum exóra.",
      "language": "both",
      "category": "maria-antifoon",
      "notes": "Maria-antifoon van Maria Lichtmis (2 februari) tot Woensdag in de Goede Week.",
      "source_url": "https://rkliturgie.nl/algemene-of-dagelijkse-gebeden-en-oefeningen/gegroet-gij-hemelkoningin-ave-regina-caelorum"
    }
  ]
};
